name: poem
description: "A Flutter app for creating and sharing poems."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  l: ^5.0.0
  pure: ^0.3.0
  sentry_flutter: ^8.14.1
  stream_transform: ^2.1.1
  flutter_native_splash: ^2.4.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: any
  supabase_flutter: ^2.8.2
  control: ^0.2.0
  octopus: ^0.0.9
  meta: ^1.15.0
  collection: ^1.19.0
  uuid: ^4.5.1
  file_picker: ^10.1.2
  cross_file: ^0.3.4+2
  pinput: ^5.0.1
  flutter_quill: ^11.4.0
  dart_openai: ^5.1.0
  path: ^1.9.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  keyboard_actions: ^4.2.0
  just_audio: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.2
  json_serializable: ^6.7.1

  flutter_gen_runner: ^5.3.1

  intl_utils: ^2.8.7

flutter_gen:
  output: lib/src/core/resources

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/core/localization/translations
  output_dir: lib/src/core/localization/generated
